apiVersion: batch/v1
kind: Job
metadata:
  name: nodejs-job
spec:
  template:
    spec:
      containers:
      - name: nodejs-container
        image: registry.hsrn.nyu.edu/vip/corelink-examples/corelink-consumer:latest
        command: ["node"]
        args: ["./receiver_fin.js"]
      restartPolicy: Never
  backoffLimit: 0
